In [260]:
import pandas as pd

In [261]:
matches = pd.read_csv("../datasets/matches.csv", index_col=0)

In [262]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City

In [263]:
matches.shape

(1389, 27)

## EDA + fixing the data

In [ ]:
matches["team"].value_counts()

team
Manchester United           72
West Ham United             72
Newcastle United            72
Brighton and Hove Albion    72
Southampton                 72
Manchester City             71
Arsenal                     71
Tottenham Hotspur           71
Wolverhampton Wanderers     71
Crystal Palace              71
Leeds United                71
Burnley                     71
Chelsea                     70
Leicester City              70
Aston Villa                 70
Everton                     70
Liverpool                   38
Fulham                      38
West Bromwich Albion        38
Sheffield United            38
Brentford                   34
Watford                     33
Norwich City                33
Name: count, dtype: int64

In [265]:
matches["opponent"].value_counts()

opponent
Southampton        71
Liverpool          71
Newcastle Utd      71
Tottenham          70
Brighton           70
Manchester Utd     70
West Ham           70
Wolves             70
Arsenal            69
Burnley            69
Crystal Palace     69
Aston Villa        69
Leeds United       69
Manchester City    69
Leicester City     68
Chelsea            68
Everton            68
Sheffield Utd      38
Fulham             38
West Brom          38
Brentford          32
Norwich City       31
Watford            31
Name: count, dtype: int64

In [266]:
team_map = {
    "Manchester Utd": "Manchester United",
    "West Ham": "West Ham United",
    "Newcastle Utd": "Newcastle United",
    "Brighton": "Brighton and Hove Albion",
    "Southampton": "Southampton",
    "Manchester City": "Manchester City",
    "Arsenal": "Arsenal",
    "Tottenham": "Tottenham Hotspur",
    "Wolves": "Wolverhampton Wanderers",
    "Crystal Palace": "Crystal Palace",
    "Leeds United": "Leeds United",
    "Burnley": "Burnley",
    "Chelsea": "Chelsea",
    "Leicester City": "Leicester City",
    "Aston Villa": "Aston Villa",
    "Everton": "Everton",
    "Liverpool": "Liverpool",
    "Fulham": "Fulham",
    "West Brom": "West Bromwich Albion",
    "Sheffield Utd": "Sheffield United",
    "Brentford": "Brentford",
    "Watford": "Watford",
    "Norwich City": "Norwich City",
}

# team column names and opponent column names do not match for corresponding teams --- fix \/ 
matches["opponent"] = matches["opponent"].replace(team_map)

In [267]:
matches[matches["team"] == "Liverpool"]

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2020-09-12,17:30,Premier League,Matchweek 1,Sat,Home,W,4.0,3.0,Leeds United,...,Match Report,NaN,20.0,4.0,17.0,0.0,2.0,2.0,2021,Liverpool
2,2020-09-20,16:30,Premier League,Matchweek 2,Sun,Away,W,2.0,0.0,Chelsea,...,Match Report,NaN,17.0,5.0,17.7,1.0,0.0,0.0,2021,Liverpool
4,2020-09-28,20:00,Premier League,Matchweek 3,Mon,Home,W,3.0,1.0,Arsenal,...,Match Report,NaN,21.0,9.0,16.8,0.0,0.0,0.0,2021,Liverpool
6,2020-10-04,19:15,Premier League,Matchweek 4,Sun,Away,L,2.0,7.0,Aston Villa,...,Match Report,NaN,14.0,8.0,15.8,1.0,0.0,0.0,2021,Liverpool
7,2020-10-17,12:30,Premier League,Matchweek 5,Sat,Away,D,2.0,2.0,Everton,...,Match Report,NaN,22.0,8.0,15.0,1.0,0.0,0.0,2021,Liverpool
9,2020-10-24,20:00,Premier League,Matchweek 6,Sat,Home,W,2.0,1.0,Sheffield United,...,Match Report,NaN,17.0,5.0,18.2,1.0,0.0,0.0,2021,Liverpool
11,2020-10-31,17:30,Premier League,Matchweek 7,Sat,Home,W,2.0,1.0,West Ham United,...,Match Report,NaN,8.0,2.0,18.6,1.0,1.0,1.0,2021,Liverpool
13,2020-11-08,16:30,Premier League,Matchweek 8,Sun,Away,D,1.0,1.0,Manchester City,...,Match Report,NaN,9.0,2.0,21.5,0.0,1.0,1.0,2021,Liverpool
14,2020-11-22,19:15,Premier League,Matchweek 9,Sun,Home,W,3.0,0.0,Leicester City,...,Match Report,NaN,24.0,12.0,11.9,0.0,0.0,0.0,2021,Liverpool
16,2020-11-28,12:30,Premier League,Matchweek 10,Sat,Away,D,1.0,1.0,Brighton and Hove Albion,...,Match Report,NaN,6.0,2.0,20.9,0.0,0.0,0.0,2021,Liverpool
18,2020-12-06,19:15,Premier League,Matchweek 11,Sun,Home,W,4.0,0.0,Wolverhampton Wanderers,...,Match Report,NaN,11.0,6.0,16.6,1.0,0.0,0.0,2021,Liverpool
20,2020-12-13,16:30,Premier League,Matchweek 12,Sun,Away,D,1.0,1.0,Fulham,...,Match Report,NaN,11.0,5.0,20.0,1.0,1.0,1.0,2021,Liverpool
21,2020-12-16,20:00,Premier League,Matchweek 13,Wed,Home,W,2.0,1.0,Tottenham Hotspur,...,Match Report,NaN,17.0,11.0,15.5,0.0,0.0,0.0,2021,Liverpool
22,2020-12-19,12:30,Premier League,Matchweek 14,Sat,Away,W,7.0,0.0,Crystal Palace,...,Match Report,NaN,14.0,7.0,13.2,1.0,0.0,0.0,2021,Liverpool
23,2020-12-27,16:30,Premier League,Matchweek 15,Sun,Home,D,1.0,1.0,West Bromwich Albion,...,Match Report,NaN,17.0,2.0,17.8,2.0,0.0,0.0,2021,Liverpool
24,2020-12-30,20:00,Premier League,Matchweek 16,Wed,Away,D,0.0,0.0,Newcastle United,...,Match Report,NaN,11.0,4.0,16.7,0.0,0.0,0.0,2021,Liverpool
25,2021-01-04,20:00,Premier League,Matchweek 17,Mon,Away,L,0.0,1.0,Southampton,...,Match Report,NaN,17.0,1.0,14.3,0.0,0.0,0.0,2021,Liverpool
27,2021-01-17,16:30,Premier League,Matchweek 19,Sun,Home,D,0.0,0.0,Manchester United,...,Match Report,NaN,17.0,3.0,17.1,0.0,0.0,0.0,2021,Liverpool
28,2021-01-21,20:00,Premier League,Matchweek 18,Thu,Home,L,0.0,1.0,Burnley,...,Match Report,NaN,27.0,6.0,17.3,0.0,0.0,0.0,2021,Liverpool
30,2021-01-28,20:00,Premier League,Matchweek 20,Thu,Away,W,3.0,1.0,Tottenham Hotspur,...,Match Report,NaN,14.0,7.0,14.7,0.0,0.0,0.0,2021,Liverpool
31,2021-01-31,16:30,Premier League,Matchweek 21,Sun,Away,W,3.0,1.0,West Ham United,...,Match Report,NaN,14.0,5.0,15.3,0.0,0.0,0.0,2021,Liverpool
32,2021-02-03,20:15,Premier League,Matchweek 22,Wed,Home,L,0.0,1.0,Brighton and Hove Albion,...,Match Report,NaN,11.0,0.0,19.9,0.0,0.0,0.0,2021,Liverpool
33,2021-02-07,16:30,Premier League,Matchweek 23,Sun,Home,L,1.0,4.0,Manchester City,...,Match Report,NaN,7.0,2.0,17.9,1.0,1.0,1.0,2021,Liverpool
34,2021-02-13,12:30,Premier League,Matchweek 24,Sat,Away,L,1.0,3.0,Leicester City,...,Match Report,NaN,15.0,4.0,15.4,2.0,0.0,0.0,2021,Liverpool
36,2021-02-20,17:30,Premier League,Matchweek 25,Sat,Home,L,0.0,2.0,Everton,...,Match Report,NaN,16.0,6.0,15.9,1.0,0.0,0.0,2021,Liverpool
37,2021-02-28,19:15,Premier League,Matchweek 26,Sun,Away,W,2.0,0.0,Sheffield United,...,Match Report,NaN,15.0,8.0,14.2,0.0,0.0,0.0,2021,Liverpool
38,2021-03-04,20:15,Premier League,Matchweek 29,Thu,Home,L,0.0,1.0,Chelsea,...,Match Report,NaN,7.0,1.0,18.4,0.0,0.0,0.0,2021,Liverpool
39,2021-03-07,14:00,Premier League,Matchweek 27,Sun,Home,L,0.0,1.0,Fulham,...,Match Report,NaN,16.0,3.0,17.0,1.0,0.0,0.0,2021,Liverpool
41,2021-03-15,20:00,Premier League,Matchweek 28,Mon,Away,W,1.0,0.0,Wolverhampton Wanderers,...,Match Report,NaN,12.0,4.0,15.9,0.0,0.0,0.0,2021,Liverpool
42,2021-04-03,20:00,Premier League,Matchweek 30,Sat,Away,W,3.0,0.0,Arsenal,...,Match Report,NaN,16.0,7.0,17.0,0.0,0.0,0.0,2021,Liverpool
44,2021-04-10,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,1.0,Aston Villa,...,Match Report,NaN,23.0,8.0,16.7,1.0,0.0,0.0,2021,Liverpool
46,2021-04-19,20:00,Premier League,Matchweek 32,Mon,Away,D,1.0,1.0,Leeds United,...,Match Report,NaN,17.0,7.0,15.7,0.0,0.0,0.0,2021,Liverpool
47,2021-04-24,12:30,Premier League,Matchweek 33,Sat,Home,D,1.0,1.0,Newcastle United,...,Match Report,NaN,21.0,9.0,17.0,1.0,0.0,0.0,2021,Liverpool
48,2021-05-08,20:15,Premier League,Matchweek 35,Sat,Home,W,2.0,0.0,Southampton,...,Match Report,NaN,14.0,6.0,12.4,0.0,0.0,0.0,2021,Liverpool
49,2021-05-13,20:15,Premier League,Matchweek 34,Thu,Away,W,4.0,2.0,Manchester United,...,Match Report,NaN,17.0,8.0,14.9,0.0,0.0,0.0,2021,Liverpool
50,2021-05-16,16:30,Premier League,Matchweek 36,Sun,Away,W,2.0,1.0,West Bromwich Albion,...,Match Report,NaN,26.0,6.0,16.9,1.0,0.0,0.0,2021,Liverpool
51,2021-05-19,20:15,Premier League,Matchweek 37,Wed,Away,W,3.0,0.0,Burnley,...,Match Report,NaN,20.0,3.0,15.5,1.0,0.0,0.0,2021,Liverpool
52,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,2.0,0.0,Crystal Palace,...,Match Report,NaN,19.0,5.0,14.2,1.0,0.0,0.0,2021,Liverpool

In [268]:
matches["round"].value_counts()

round
Matchweek 1     39
Matchweek 2     39
Matchweek 3     39
Matchweek 4     39
Matchweek 5     39
Matchweek 6     39
Matchweek 7     39
Matchweek 8     39
Matchweek 9     39
Matchweek 10    39
Matchweek 11    39
Matchweek 12    39
Matchweek 13    39
Matchweek 14    39
Matchweek 15    39
Matchweek 16    39
Matchweek 17    39
Matchweek 19    39
Matchweek 20    39
Matchweek 23    39
Matchweek 24    39
Matchweek 25    39
Matchweek 26    39
Matchweek 28    39
Matchweek 29    39
Matchweek 31    39
Matchweek 32    39
Matchweek 34    39
Matchweek 18    37
Matchweek 21    37
Matchweek 22    37
Matchweek 27    37
Matchweek 30    37
Matchweek 33    32
Matchweek 35    20
Matchweek 36    20
Matchweek 37    20
Matchweek 38    20
Name: count, dtype: int64

In [269]:
matches.dtypes

date                str
time                str
comp                str
round               str
day                 str
venue               str
result              str
gf              float64
ga              float64
opponent            str
xg              float64
xga             float64
poss            float64
attendance      float64
captain             str
formation           str
referee             str
match report        str
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team                str
dtype: object

In [270]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [271]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,notes,sh,sot,dist,fk,pk,pkatt,season,team,venue_code
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham Hotspur,...,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City,0
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City,1
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City,1
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City,0
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0.0,4.0,Tottenham Hotspur,...,NaN,8.0,1.0,17.4,0.0,0.0,0.0,2021,Sheffield United,0
39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0.0,2.0,Crystal Palace,...,NaN,7.0,0.0,11.4,1.0,0.0,0.0,2021,Sheffield United,1
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1.0,0.0,Everton,...,NaN,10.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United,0
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0.0,1.0,Newcastle United,...,NaN,11.0,1.0,16.0,1.0,0.0,0.0,2021,Sheffield United,0
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1.0,0.0,Burnley,...,NaN,12.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United,1

In [272]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [273]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,sh,sot,dist,fk,pk,pkatt,season,team,venue_code,opp_code
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham Hotspur,...,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City,0,18
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City,1,15
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City,1,0
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City,0,10
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0.0,4.0,Tottenham Hotspur,...,8.0,1.0,17.4,0.0,0.0,0.0,2021,Sheffield United,0,18
39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0.0,2.0,Crystal Palace,...,7.0,0.0,11.4,1.0,0.0,0.0,2021,Sheffield United,1,6
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1.0,0.0,Everton,...,10.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United,0,7
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0.0,1.0,Newcastle United,...,11.0,1.0,16.0,1.0,0.0,0.0,2021,Sheffield United,0,14
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1.0,0.0,Burnley,...,12.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United,1,4

In [274]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [275]:
matches["date"] = pd.to_datetime(matches["date"])

In [276]:
matches["day_code"] = matches["date"].dt.dayofweek

In [277]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,dist,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham Hotspur,...,16.9,1.0,0.0,0.0,2022,Manchester City,0,18,16,6
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,17.3,1.0,0.0,0.0,2022,Manchester City,1,15,15,5
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,14.3,0.0,0.0,0.0,2022,Manchester City,1,0,12,5
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,14.0,0.0,0.0,0.0,2022,Manchester City,0,10,15,5
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,15.7,1.0,0.0,0.0,2022,Manchester City,1,17,15,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0.0,4.0,Tottenham Hotspur,...,17.4,0.0,0.0,0.0,2021,Sheffield United,0,18,19,6
39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0.0,2.0,Crystal Palace,...,11.4,1.0,0.0,0.0,2021,Sheffield United,1,6,15,5
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1.0,0.0,Everton,...,17.0,0.0,0.0,0.0,2021,Sheffield United,0,7,19,6
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0.0,1.0,Newcastle United,...,16.0,1.0,0.0,0.0,2021,Sheffield United,0,14,18,2
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1.0,0.0,Burnley,...,17.0,0.0,0.0,0.0,2021,Sheffield United,1,4,16,6

In [278]:
matches["target"] = matches["result"].astype("category").cat.codes

# W - 2
# L - 1
# D - 0

In [341]:
matches["target"].value_counts()

target
1    548
2    526
0    315
Name: count, dtype: int64

## Training Model

In [280]:
from sklearn.ensemble import  RandomForestClassifier

In [281]:
rf1 = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [ ]:
# 
# split
train = matches[matches["date"] < "2022-01-01"]

In [283]:
# test split
test = matches[matches["date"] > "2022-01-01"]

In [284]:
# features to base the prediction on
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [285]:
rf1.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [286]:
predictions = rf1.predict(test[predictors])

In [287]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(test["target"], predictions)   # how many predictions the model got right

In [288]:
acc

0.4384057971014493

In [289]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(test["target"], predictions)

In [290]:
print(cm)

[[ 9 21 26]
 [29 62 25]
 [18 36 50]]

In [291]:
combined = pd.DataFrame(dict(actual=test["target"], prediction=predictions))

In [292]:
combined

    actual  prediction
31       2           1
32       0           2
34       2           0
35       2           2
37       1           2
..     ...         ...
33       1           0
34       0           2
35       2           2
36       1           1
37       1           2

[276 rows x 2 columns]

In [293]:
# user friendly confusion matrix
pd.crosstab(index=combined["actual"].values, columns=combined["prediction"].values, rownames=["actual"], colnames=["prediction"])

prediction   0   1   2
actual
0            9  21  26
1           29  62  25
2           18  36  50

In [294]:
from sklearn.metrics import classification_report

cr = classification_report(test["target"], predictions)

In [295]:
print(cr)

              precision    recall  f1-score   support

           0       0.16      0.16      0.16        56
           1       0.52      0.53      0.53       116
           2       0.50      0.48      0.49       104

    accuracy                           0.44       276
   macro avg       0.39      0.39      0.39       276
weighted avg       0.44      0.44      0.44       276

In [296]:
from sklearn.metrics import precision_score

In [297]:
ps = precision_score(test["target"], predictions, average=None)

In [298]:
type(ps)

numpy.ndarray

In [299]:
class_names = ["Draw", "Loss", "Win"]

for cat, score in zip(class_names, ps):
    print(f"{cat}: {score:.2f}")

Draw: 0.16
Loss: 0.52
Win: 0.50

In [300]:
def precision_display(ps):
    for clazz, score in zip(rf1.classes_, ps):
        print(f"Class {clazz}: {score:.2f}")

In [301]:
precision_display(ps)

Class 0: 0.16
Class 1: 0.52
Class 2: 0.50

In [302]:
# predictors = ["venue_code", "opp_code", "hour", "day_code"]

def print_importances(model, predictors):
    importances = model.feature_importances_  
    pairs = zip(importances, predictors)
    sorted_pairs = sorted(pairs, reverse=True)
    for imp, feat in sorted_pairs:
        print(f"{feat}: {imp:.2f}")

In [303]:
print_importances(rf1, predictors)

opp_code: 0.55
hour: 0.20
day_code: 0.17
venue_code: 0.08

## Improving precision

In [304]:
rf2 = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [305]:
grouped_matches = matches.groupby("team")

In [306]:
group = grouped_matches.get_group("Manchester United")

In [307]:
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2021-08-14,12:30,Premier League,Matchweek 1,Sat,Home,W,5.0,1.0,Leeds United,...,0.0,0.0,0.0,2022,Manchester United,1,9,12,5,2
1,2021-08-22,14:00,Premier League,Matchweek 2,Sun,Away,D,1.0,1.0,Southampton,...,1.0,0.0,0.0,2022,Manchester United,0,17,14,6,0
2,2021-08-29,16:30,Premier League,Matchweek 3,Sun,Away,W,1.0,0.0,Wolverhampton Wanderers,...,1.0,0.0,0.0,2022,Manchester United,0,22,16,6,2
3,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,1.0,Newcastle United,...,0.0,0.0,0.0,2022,Manchester United,1,14,15,5,2
5,2021-09-19,14:00,Premier League,Matchweek 5,Sun,Away,W,2.0,1.0,West Ham United,...,0.0,0.0,0.0,2022,Manchester United,0,21,14,6,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,2021-05-09,14:05,Premier League,Matchweek 35,Sun,Away,W,3.0,1.0,Aston Villa,...,0.0,1.0,1.0,2021,Manchester United,0,1,14,6,2
56,2021-05-11,18:00,Premier League,Matchweek 36,Tue,Home,L,1.0,2.0,Leicester City,...,0.0,0.0,0.0,2021,Manchester United,1,10,18,1,1
57,2021-05-13,20:15,Premier League,Matchweek 34,Thu,Home,L,2.0,4.0,Liverpool,...,1.0,0.0,0.0,2021,Manchester United,1,11,20,3,1
58,2021-05-18,18:00,Premier League,Matchweek 37,Tue,Home,D,1.0,1.0,Fulham,...,2.0,0.0,0.0,2021,Manchester United,1,8,18,1,0
59,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Away,W,2.0,1.0,Wolverhampton Wanderers,...,0.0,1.0,1.0,2021,Manchester United,0,22,16,6,2

In [308]:
# basically compute rolling average of goals scored of past three matches
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed="left").mean()   # closed="left" closes the range on the left, opens on the right (current)
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [309]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{el}_rolling" for el in cols]

In [310]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [311]:
# for Manchester United
rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
5,2020-10-17,20:00,Premier League,Matchweek 5,Sat,Away,W,4.0,1.0,Newcastle United,...,5,2,1.666667,3.666667,9.000000,2.333333,19.800000,0.333333,0.666667,0.666667
7,2020-10-24,17:30,Premier League,Matchweek 6,Sat,Home,D,0.0,0.0,Chelsea,...,5,0,2.666667,3.000000,12.333333,4.666667,20.000000,0.000000,0.666667,1.000000
9,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Home,L,0.0,1.0,Arsenal,...,6,1,1.666667,2.333333,15.000000,5.333333,19.700000,0.000000,0.333333,0.666667
11,2020-11-07,12:30,Premier League,Matchweek 8,Sat,Away,W,3.0,1.0,Everton,...,5,2,1.333333,0.666667,16.666667,5.666667,18.300000,0.000000,0.000000,0.333333
12,2020-11-21,20:00,Premier League,Matchweek 9,Sat,Home,W,1.0,0.0,West Bromwich Albion,...,5,2,1.000000,0.666667,12.000000,3.666667,18.733333,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,2022-04-02,17:30,Premier League,Matchweek 31,Sat,Home,D,1.0,1.0,Leicester City,...,5,0,1.333333,2.000000,12.666667,3.666667,15.333333,0.333333,0.000000,0.000000
41,2022-04-09,12:30,Premier League,Matchweek 32,Sat,Away,L,0.0,1.0,Everton,...,5,1,1.666667,2.333333,9.000000,4.333333,14.333333,0.000000,0.000000,0.000000
42,2022-04-16,15:00,Premier League,Matchweek 33,Sat,Home,W,3.0,2.0,Norwich City,...,5,2,1.333333,1.333333,11.333333,5.000000,15.333333,0.000000,0.000000,0.000000
43,2022-04-19,20:00,Premier League,Matchweek 30,Tue,Away,L,0.0,4.0,Liverpool,...,1,1,1.333333,1.333333,14.333333,6.000000,15.666667,0.333333,0.000000,0.000000
44,2022-04-23,12:30,Premier League,Matchweek 34,Sat,Away,L,1.0,3.0,Arsenal,...,5,1,1.000000,2.333333,11.333333,4.666667,17.800000,0.333333,0.000000,0.000000

In [312]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [313]:
matches_rolling = matches_rolling.reset_index(level="team")

In [314]:
matches_rolling

,team,date,time,comp,round,day,venue,result,gf,ga,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
6,Arsenal,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,...,6,2,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
7,Arsenal,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,...,5,1,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
9,Arsenal,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0.0,1.0,...,6,1,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
11,Arsenal,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1.0,0.0,...,6,2,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
13,Arsenal,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0.0,3.0,...,6,1,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,Wolverhampton Wanderers,2022-03-13,14:00,Premier League,Matchweek 29,Sun,Away,W,1.0,0.0,...,6,2,1.333333,1.000000,12.333333,3.666667,19.300000,0.000000,0.000000,0.000000
33,Wolverhampton Wanderers,2022-03-18,20:00,Premier League,Matchweek 30,Fri,Home,L,2.0,3.0,...,4,1,1.666667,0.666667,12.333333,4.333333,19.600000,0.000000,0.000000,0.000000
34,Wolverhampton Wanderers,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,1.0,...,5,2,2.333333,1.000000,13.000000,5.333333,19.833333,0.000000,0.000000,0.000000
35,Wolverhampton Wanderers,2022-04-08,20:00,Premier League,Matchweek 32,Fri,Away,L,0.0,1.0,...,4,1,1.666667,1.333333,13.000000,5.000000,18.533333,0.000000,0.000000,0.000000
36,Wolverhampton Wanderers,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Away,L,0.0,1.0,...,6,1,1.333333,1.666667,10.000000,4.666667,17.633333,0.000000,0.000000,0.000000

In [315]:
# matches_rolling = matches_rolling.droplevel("team")

In [316]:
matches_rolling.columns

Index(['team', 'date', 'time', 'comp', 'round', 'day', 'venue', 'result', 'gf',
       'ga', 'opponent', 'xg', 'xga', 'poss', 'attendance', 'captain',
       'formation', 'referee', 'match report', 'notes', 'sh', 'sot', 'dist',
       'fk', 'pk', 'pkatt', 'season', 'venue_code', 'opp_code', 'hour',
       'day_code', 'target', 'gf_rolling', 'ga_rolling', 'sh_rolling',
       'sot_rolling', 'dist_rolling', 'fk_rolling', 'pk_rolling',
       'pkatt_rolling'],
      dtype='str')

In [317]:
matches_rolling.index = range(matches_rolling.shape[0])

In [318]:
matches_rolling

,team,date,time,comp,round,day,venue,result,gf,ga,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,Arsenal,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,...,6,2,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
1,Arsenal,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,...,5,1,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
2,Arsenal,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0.0,1.0,...,6,1,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
3,Arsenal,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1.0,0.0,...,6,2,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
4,Arsenal,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0.0,3.0,...,6,1,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1312,Wolverhampton Wanderers,2022-03-13,14:00,Premier League,Matchweek 29,Sun,Away,W,1.0,0.0,...,6,2,1.333333,1.000000,12.333333,3.666667,19.300000,0.000000,0.000000,0.000000
1313,Wolverhampton Wanderers,2022-03-18,20:00,Premier League,Matchweek 30,Fri,Home,L,2.0,3.0,...,4,1,1.666667,0.666667,12.333333,4.333333,19.600000,0.000000,0.000000,0.000000
1314,Wolverhampton Wanderers,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,1.0,...,5,2,2.333333,1.000000,13.000000,5.333333,19.833333,0.000000,0.000000,0.000000
1315,Wolverhampton Wanderers,2022-04-08,20:00,Premier League,Matchweek 32,Fri,Away,L,0.0,1.0,...,4,1,1.666667,1.333333,13.000000,5.000000,18.533333,0.000000,0.000000,0.000000
1316,Wolverhampton Wanderers,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Away,L,0.0,1.0,...,6,1,1.333333,1.666667,10.000000,4.666667,17.633333,0.000000,0.000000,0.000000

In [319]:
def make_predictions(data, predictors):
    train = data[data["date"] < "2022-01-01"]
    test = data[data["date"] > "2022-01-01"]
    rf2.fit(train[predictors], train["target"])
    predictions = rf2.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], prediction=predictions))
    ps = precision_score(test["target"], predictions, average=None)
    
    return combined, ps

In [320]:
combined, precision = make_predictions(matches_rolling, predictors + new_cols)

In [321]:
combined

      actual  prediction
55         0           2
56         2           2
57         2           2
58         2           2
59         2           2
...      ...         ...
1312       2           1
1313       1           1
1314       2           1
1315       1           2
1316       1           1

[276 rows x 2 columns]

In [322]:
print(f"NEW MODEL")
precision_display(precision)

NEW MODEL
Class 0: 0.27
Class 1: 0.52
Class 2: 0.54

In [342]:
combined["actual"].value_counts()

actual
1    116
2    104
0     56
Name: count, dtype: int64

In [323]:
print(f"OLD MODEL")
precision_display(ps)

OLD MODEL
Class 0: 0.16
Class 1: 0.52
Class 2: 0.50

In [343]:
train["target"].value_counts()

target
1    429
2    419
0    259
Name: count, dtype: int64

In [324]:
print(f"NEW MODEL")
print_importances(rf2, predictors + new_cols)

NEW MODEL
dist_rolling: 0.16
opp_code: 0.15
sh_rolling: 0.14
sot_rolling: 0.11
ga_rolling: 0.10
gf_rolling: 0.09
hour: 0.06
fk_rolling: 0.06
day_code: 0.05
pkatt_rolling: 0.03
pk_rolling: 0.02
venue_code: 0.02

In [325]:
print(f"OLD MODEL")
print_importances(rf1, predictors)

OLD MODEL
opp_code: 0.55
hour: 0.20
day_code: 0.17
venue_code: 0.08

In [326]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [327]:
combined.index = range(combined.shape[0])

In [328]:
combined
# D - 0
# L - 1
# W - 2

,actual,prediction,date,team,opponent,result
0,0,2,2022-01-23,Arsenal,Burnley,D
1,2,2,2022-02-10,Arsenal,Wolverhampton Wanderers,W
2,2,2,2022-02-19,Arsenal,Brentford,W
3,2,2,2022-02-24,Arsenal,Wolverhampton Wanderers,W
4,2,2,2022-03-06,Arsenal,Watford,W
...,...,...,...,...,...,...
271,2,1,2022-03-13,Wolverhampton Wanderers,Everton,W
272,1,1,2022-03-18,Wolverhampton Wanderers,Leeds United,L
273,2,1,2022-04-02,Wolverhampton Wanderers,Aston Villa,W
274,1,2,2022-04-08,Wolverhampton Wanderers,Newcastle United,L
275,1,1,2022-04-24,Wolverhampton Wanderers,Burnley,L

In [337]:
matches_rolling["team"].value_counts()

team
Brighton and Hove Albion    69
Manchester United           69
Newcastle United            69
Southampton                 69
West Ham United             69
Arsenal                     68
Burnley                     68
Leeds United                68
Manchester City             68
Tottenham Hotspur           68
Wolverhampton Wanderers     68
Aston Villa                 67
Chelsea                     67
Everton                     67
Leicester City              67
Crystal Palace              65
Fulham                      35
Liverpool                   35
Sheffield United            35
West Bromwich Albion        35
Brentford                   31
Norwich City                30
Watford                     30
Name: count, dtype: int64

In [338]:
matches["team"].value_counts()

team
Manchester United           72
West Ham United             72
Newcastle United            72
Brighton and Hove Albion    72
Southampton                 72
Manchester City             71
Arsenal                     71
Tottenham Hotspur           71
Wolverhampton Wanderers     71
Crystal Palace              71
Leeds United                71
Burnley                     71
Chelsea                     70
Leicester City              70
Aston Villa                 70
Everton                     70
Liverpool                   38
Fulham                      38
West Bromwich Albion        38
Sheffield United            38
Brentford                   34
Watford                     33
Norwich City                33
Name: count, dtype: int64

In [ ]:
combined
# D - 0
# L - 1
# W - 2

,actual,prediction,date,team,opponent,result
0,0,2,2022-01-23,Arsenal,Burnley,D
1,2,2,2022-02-10,Arsenal,Wolverhampton Wanderers,W
2,2,2,2022-02-19,Arsenal,Brentford,W
3,2,2,2022-02-24,Arsenal,Wolverhampton Wanderers,W
4,2,2,2022-03-06,Arsenal,Watford,W
...,...,...,...,...,...,...
271,2,1,2022-03-13,Wolverhampton Wanderers,Everton,W
272,1,1,2022-03-18,Wolverhampton Wanderers,Leeds United,L
273,2,1,2022-04-02,Wolverhampton Wanderers,Aston Villa,W
274,1,2,2022-04-08,Wolverhampton Wanderers,Newcastle United,L
275,1,1,2022-04-24,Wolverhampton Wanderers,Burnley,L

In [345]:
combined[combined["team"] == "Arsenal"]

    actual  prediction       date     team                  opponent result
0        0           2 2022-01-23  Arsenal                   Burnley      D
1        2           2 2022-02-10  Arsenal   Wolverhampton Wanderers      W
2        2           2 2022-02-19  Arsenal                 Brentford      W
3        2           2 2022-02-24  Arsenal   Wolverhampton Wanderers      W
4        2           2 2022-03-06  Arsenal                   Watford      W
5        2           2 2022-03-13  Arsenal            Leicester City      W
6        1           2 2022-03-16  Arsenal                 Liverpool      L
7        2           1 2022-03-19  Arsenal               Aston Villa      W
8        1           1 2022-04-04  Arsenal            Crystal Palace      L
9        1           1 2022-04-09  Arsenal  Brighton and Hove Albion      L
10       1           2 2022-04-16  Arsenal               Southampton      L
11       2           1 2022-04-20  Arsenal                   Chelsea      W
12       2           1 2022-04-23  Arsenal         Manchester United      W

In [347]:
combined[combined["team"] == "Brentford"]

    actual  prediction       date       team                 opponent result
27       2           1 2022-01-02  Brentford              Aston Villa      W
28       1           0 2022-01-11  Brentford              Southampton      L
29       1           1 2022-01-16  Brentford                Liverpool      L
30       1           1 2022-01-19  Brentford        Manchester United      L
31       1           1 2022-01-22  Brentford  Wolverhampton Wanderers      L
32       1           1 2022-02-09  Brentford          Manchester City      L
33       0           1 2022-02-12  Brentford           Crystal Palace      D
34       1           1 2022-02-19  Brentford                  Arsenal      L
35       1           1 2022-02-26  Brentford         Newcastle United      L
36       2           1 2022-03-05  Brentford             Norwich City      W
37       2           1 2022-03-12  Brentford                  Burnley      W
38       1           1 2022-03-20  Brentford           Leicester City      L
39       2           1 2022-04-02  Brentford                  Chelsea      W
40       2           2 2022-04-10  Brentford          West Ham United      W
41       2           2 2022-04-16  Brentford                  Watford      W
42       0           2 2022-04-23  Brentford        Tottenham Hotspur      D